backend:
  name: git-gateway
  branch: master # Branch to update (optional; defaults to master)

media_folder: "public/uploads" # Media files will be stored in the repo under public/uploads
public_folder: "/uploads" # Folder path where uploaded files will be accessed, relative to the base of the built site

collections:
  - label: "Pages"
    name: "pages"
    files:
      - label: "Home Page"
        name: "home"
        file: "src/pages/home.md"
        fields:
          - {label: Title, name: title, widget: string}
          - {label: Date, name: date, widget: date}
          - {label: Paragraph 1, name: p1, widget: text}
      - label: "About Page"
        name: "about"
        file: "src/pages/about.md"
        fields:
          - {label: Title, name: title, widget: string}
          - {label: Date, name: date, widget: date}
          - {label: Paragraph 1, name: p1, widget: text}
         